services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - ./secrets_api.txt
    environment:
      - NODE_ENV=production

  web:
    container_name: web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - api
    env_file:
      - ./secrets_web.txt
    environment:
      - NODE_ENV=production
      - INTERNAL_API_URL=${INTERNAL_API_URL:-http://api:5000}
secrets:
  secrets_api:
    file: ./secrets_api.txt
  secrets_web:
    file: ./secrets_web.txt