export const PROFILE_MOCK = {
  name: 'Alana Smith',
  handle: '@Alana',
  email: 'asmith@acme.com',
  phone: '+61 422 537 400',
  avatarInitials: 'AS',
  about: [
    { id: 'role', label: 'Software Engineer', icon: 'briefcase' as const },
    {
      id: 'department',
      label: 'Engineering & Technology',
      icon: 'network' as const,
    },
    { id: 'org', label: 'Acme', icon: 'building' as const },
    {
      id: 'location',
      label: 'Lvl 2, Building 4, Mather St',
      icon: 'mapPin' as const,
    },
    {
      id: 'timezone',
      label: '3:04pm (Sydney, AEST)',
      icon: 'clock' as const,
    },
  ],
  workedOn: [
    {
      id: '1',
      title: 'Technical dept improvements plan',
      meta: 'Team documentation • You and Alana have both worked on this',
      tone: 'blue' as const,
    },
    {
      id: '2',
      title: 'Q2 feature delivery tracker',
      meta: 'Team documentation • Alana edited this 5 hours ago',
      tone: 'orange' as const,
    },
    {
      id: '3',
      title: 'Security & compliance checklist',
      meta: 'Team documentation • Alana edited this yesterday',
      tone: 'green' as const,
    },
    {
      id: '4',
      title: 'Sprint planning notes — board sync',
      meta: 'Team documentation • You updated this last week',
      tone: 'blue' as const,
    },
    {
      id: '5',
      title: 'Customer launch readiness review',
      meta: 'Team documentation • Alana commented on this',
      tone: 'orange' as const,
    },
    {
      id: '6',
      title: 'A',
      meta: 'A meta',
      tone: 'green' as const,
    },
  ],
  places: [{ id: '1bt', name: '1billionTech', subtitle: 'A company' }],
  teams: [
    {
      id: 't1',
      name: 'The A Team',
      membersLabel: '5 members',
      initials: 'AT',
    },
    {
      id: 't2',
      name: 'The Busy Bees',
      membersLabel: '4 members including you',
      initials: 'BB',
    },
    {
      id: 't3',
      name: 'City to Surf',
      membersLabel: '22 members',
      initials: 'CS',
    },
  ],
  worksWith: [
    {
      id: 'w1',
      name: 'Kate Renelds',
      handle: '@katerenelds',
      role: 'Project Manager',
      initials: 'KR',
      online: true,
    },
    {
      id: 'w2',
      name: 'Jonathan White',
      handle: '@jonwhite',
      role: 'Developer',
      initials: 'JW',
      online: true,
    },
    {
      id: 'w3',
      name: 'Emma Thompson',
      handle: '@emmathompson',
      role: 'Developer',
      initials: 'ET',
      online: true,
    },
    {
      id: 'w4',
      name: 'Harry Jones',
      handle: '@harryjones',
      role: 'CIO',
      initials: 'HJ',
      online: true,
    },
  ],
} as const;
